### ISSUE TITLE
Idea: kakship support

### ISSUE THREAD

**Issue by rochacbruno** [enricozb/tabs.kak#10]
I am using kakship https://github.com/eburghar/kakship

This is customizable via starship.toml file

I think we can create a custom component for tabs there

I just don't know where to start yet.

**Comment by enricozb** [comment]
I don't personally use kakship but I can see the desire to add a component in there. Let me know if there's any info I can provide that might be helpful to you.

**Comment by rochacbruno** [comment]
Hey thanks for the response, after trying multiple ways (and due to my lack of knowledge on kakscript) I ended up solving the issue with kakship + kks

https://github.com/eburghar/kakship/issues/4#issuecomment-1725835251 

Still missing some functionality but I can see my buffers.
