### ISSUE TITLE
Assumes that sh = bash

### ISSUE THREAD

**Issue by sgraf812** [enricozb/tabs.kak#2]
Thus this plugin isn't POSIX compatible. It doesn't work on Ubuntu, for example.

**Comment by enricozb** [comment]
Thanks for raising this issue. In 2775ab7 I've made changes to tabs.kak so it works with `KAKOUNE_POSIX_SHELL=/usr/bin/dash`, which should be very POSIX restrictive. Please let me know if tabs.kak works for you now.

**Comment by sgraf812** [comment]
Apparently the plugin loads without errors now! Thank you for the fix.

... But it doesn't display any tabs, even if I do `KAKOUNE_POSIX_SHELL=$(which bash) kak`. Not sure if that's in any way related to #1. I don't have any custom powerline plugins, but I'm using nix+home-manager to maintain my kakoune installation, so I don't use plug.kak. I'm currently hooked up to `WinCreate` to set the `modelinefmt_tabs` option.

I'm a bit too tired to tackle that now, maybe more tomorrow.

**Comment by sgraf812** [comment]
I still haven't debugged my issues, but apparently it isn't related to POSIX compliance. So I guess we can close this.

**Comment by sgraf812** [comment]
Oh, actually now I found out why the plugin doesn't work for me: I'm also using `kak-powerline` as in #1, but I previously forgot about it. If I deactivate `kak-powerline`, I see the tab bar at the bottom, as expected.
