### ISSUE TITLE
NormalIdle hook

### ISSUE THREAD

**Issue by mralusw** [enricozb/tabs.kak#6]
Is the NormalIdle hook actually necessary? I've removed it, and it doesn't seem to make `tabs.kak` any worse (or better &mdash; I see issues with `*buffers*`). If the `WinDisplay` hook is sufficient, I'd like to remove the idle call in my #5 PR

**Comment by enricozb** [comment]
What's the purpose of removing the `NormalIdle` hook?

**Comment by mralusw** [comment]
`*ldle` is among hooks that get run continuously (unlike WinDisplay, BufCreate, KakEnd etc). So, does `tabs.kak` need to update anything every time the user moves the cursor around the buffer? `kakoune-buffers` doesn't have an IdleHook.

If there's no need for an idle hook, then it seems wasteful to call `lua` (or even `sh`) gratuitiously every time the cursor moves around the window.

**Comment by enricozb** [comment]
Thanks for the PR! I remember there was a reason I added `NormalIdle` hooks, I think it had to do with the fact that if I called `delete-buffer` the tab bar wouldn't update, but I definitely understand your concern. I'm thinking of switching this away from bash at some point and instead distributing a binary.

**Comment by mralusw** [comment]
I'll check `db`... at some point. If that's the case, probably a `BufClose` hook can fix it.

Sorry to "pick on" your plugin, it's just that I use it, and I've been benchmarking plugin activity (with my [`fakesh.sh`](https://gitlab.com/kstr0k/f8ksh)). Since it installs an Idle hook, yours obviously shows up consistently.

**Comment by enricozb** [comment]
This `fakesh.sh` is pretty cool! I'm pushing a binary to a separate branch to see if I can skip bash entirely, seems to be much faster. I'll let you know once it's ready for testing.

**Comment by mralusw** [comment]
So glad you liked it.

It's external-command invocations that usually kill shell performance, unless you use an [applet-biased busybox](https://gitlab.com/kstr0k/f8ksh#applet-biased-busybox) (e.g. `/bin/static-sh` on Debians).

IIRC your code has a single call to external utilities left (`tail -c`), which *is* a BusyBox built-in, and could also be emulated with pure shell code (for example, using a ['`????...`' pattern](https://gitlab.com/kstr0k/fast-context.kak/-/blob/master/rc/context#L56) as in my [fast-context.kak](https://gitlab.com/kstr0k/fast-context.kak) plugin).

So, if you want to compare, you may want to try getting rid of the final external command invocation (either via `static-sh`, or by truncating in shell). Otherwise, yeah, a binary will obviously win: we're comparing a single external `tail -c` call plus shell code, to a single external binary call.

**Comment by mralusw** [comment]
... but I think the real problem here is the idle hook. Without that, there's little need to optimize. I think a WinDisplay hook, plus BufCreate and BufClose (in case you change "background" buffers, not the current one) should cover all cases
